before_script:
  - export PATH=/opt/Catapult-10.3a/Mgc_home/bin:$PATH
  - export LM_LICENSE_FILE=1717@licence.irisa.fr:2100@licence.irisa.fr
  - mkdir -p cache

cache:
  paths:
    - cache

stages:
  - build
  - test
  - HLS

# Note: we cannot use submodule commit as cache key, so we do it manually in
# subfolder of a big cache
cbuild:
  stage: build
  artifacts:
    paths:
      - build/bin
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make all

catapult_ASIC:
  stage: HLS
  artifacts:
    paths:
      - comet.vhdl
    expire_in: 200y
  script:
    - mkdir build-catapult-asic
    - cd build-catapult-asic
    - catapult -shell -file $CI_PROJECT_DIR/scripts/catapult_asic.tcl
    - mv Catapult/doCore.v1/concat_rtl.vhdl ../comet.vhdl

catapult_Xilinx:
  stage: HLS
  artifacts:
    paths:
      - comet.vhdl
    expire_in: 200y
  script:
    - mkdir build-catapult-xilinx
    - cd build-catapult-xilinx
    - catapult -shell -file $CI_PROJECT_DIR/scripts/catapult_xilinx.tcl
    - mv Catapult/doCore.v1/concat_rtl.vhdl ../comet.vhdl

test:atomic:
  stage: test
  script:
    - cd build/bin
    - ./atomicTests $CI_PROJECT_DIR/tests/atomicTests

test:applications:
  stage: test
  script:
    - cd tests
    - ./runTests.sh
    
    
test:float:
	stage: test
	script:
	-cd build/bin
	- ./testFPU
