#!/usr/bin/env python3

import pickle, argparse, pdb
import matplotlib.pyplot as plt

def buildHistogram(patternList):
    #define a list of the different bit counters
    bitCounters = [0]*len(patternList[0][0])
    for p, c in zip(patternList[0], patternList[1]):    #pattern per pattern
        for bitPosition in range(len(p)):
            if p[bitPosition] == '1':
                bitCounters[bitPosition] += c
    for i in range(len(bitCounters)):
        bitCounters[i] /= 1000000
    return bitCounters


def main():
    #parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("inputFile", type=str, help="path to the patterns base")
    args = parser.parse_args()

    #load the patterns data
    patterns = pickle.load(open(args.inputFile, 'rb'))

    #build histgrams per region
    for region in patterns.keys():
        hist = buildHistogram(patterns[region])
        plt.figure()
        #plt.step(range(len(hist)), weights=hist, histtype='bar', rwidth=0.8)
        plt.bar(range(len(hist)), hist)
        plt.title(region)
        plt.xlabel('bit position')
        plt.ylabel('error probability')
        plt.grid(color='k', linestyle=':', linewidth=0.5)
    plt.show()


if __name__ == "__main__":
    main()
