#!/usr/bin/env python3


import pickle, pdb
import matplotlib.pyplot as plt
import argparse

################################################################################
#               Main
################################################################################

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("inputFile", type=str, help="path to the result base")
    args = parser.parse_args()

    #format arguments
    inputFilePath = args.inputFile

    #open the result base
    inputFile = open(inputFilePath, 'rb')
    results = pickle.load(inputFile)
    inputFile.close()

    


if __name__ == "__main__":
    # execute only if run as a script
    main()
